**7.3. Load CSV, Excel and Parquet Files**

Load three common dataset formats used in Machine Learning:

- CSV files

- Excel files

- Parquet files

In [1]:
# install the required libraries
%pip install -q pandas openpyxl pyarrow
# restart the kernel to use the updated packages

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.1.2 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
import os

load CSV file

In [3]:
df_csv = pd.read_csv("titanic.csv")

In [4]:
type(df_csv)

pandas.DataFrame

In [5]:
print(df_csv.head())

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S

In [7]:
# load selected columns
df_csv_subset = pd.read_csv(
    filepath_or_buffer="titanic.csv",
    usecols=["Survived","Pclass","Age","Fare"]
)

In [8]:
df_csv_subset.head()

   Survived  Pclass   Age     Fare
0         0       3  22.0   7.2500
1         1       1  38.0  71.2833
2         1       3  26.0   7.9250
3         1       1  35.0  53.1000
4         0       3  35.0   8.0500

In [9]:
# Load first n rows
df_csv_preview = pd.read_csv("titanic.csv",nrows=5)

In [10]:
df_csv_preview.shape

(5, 12)

Load Excel file

In [11]:
df_excel = pd.read_excel("titanic.xlsx")

In [12]:
df_excel.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [18]:
# load selected columns
df_excel_subset = pd.read_excel(
    io="titanic.xlsx",
    usecols=["Survived","Pclass","Age","Fare"]
)

In [19]:
df_excel_subset.head()

   Survived  Pclass   Age     Fare
0         0       3  22.0   7.2500
1         1       1  38.0  71.2833
2         1       3  26.0   7.9250
3         1       1  35.0  53.1000
4         0       3  35.0   8.0500

In [25]:
df_excel_subset.shape

(891, 4)

In [26]:
# check sheet names
xls = pd.ExcelFile("titanic.xlsx")
print(xls.sheet_names)

['Sheet1']

In [35]:
df_excel_sheet = pd.read_excel("titanic.xlsx", sheet_name="Sheet1")
df_excel_sheet.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

load the parquet file

In [ ]:
# all method of csv or excel would be simillar for this also

df_parquet = pd.read_parquet("titanic.parquet")
df_parquet.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

load the csv file with different separator

In [32]:
df_tab = pd.read_csv("titanic_tab.csv",sep="\t")
df_tab.shape

(891, 12)

Compare file size

In [33]:
def file_size(path):
    size_bytes = os.path.getsize(path)
    size_kb = round(size_bytes/1024,2)
    size_mb = round(size_bytes/(1024 * 1024),4)
    return size_kb,size_mb

for f in ["titanic.csv","titanic.parquet","titanic.xlsx","titanic_tab.csv"]:
    kb,mb = file_size(f)
    print(f"{f} : {kb}kb and {mb}mb")

titanic.csv : 58.89kb and 0.0575mb
titanic.parquet : 40.43kb and 0.0395mb
titanic.xlsx : 67.22kb and 0.0656mb
titanic_tab.csv : 58.91kb and 0.0575mb